name: tutorial
dependencies:
  - python=3.7
  - dask
  - distributed
  - h5py
  - ipywidgets
  - jupyterlab
  - matplotlib
  - nodejs
  - pandas
  - pyarrow
  - pygraphviz
  - python-graphviz
  - seaborn
